//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowbreakBox.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowbreakBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemSettings]
        ///rhi.SyncInterval=1
        ///rhi.SyncSlackMS=0
        ///r.GTSyncType=2
        ///r.OneFrameThreadLag=1
        ///r.VSync=1
        ///r.Streaming.NumStaticComponentsProcessedPerFrame=10
        ///s.LevelStreamingComponentsUnregistrationGranularity=5
        ///s.LevelStreamingComponentsRegistrationGranularity=5
        ///s.AsyncLoadingTimeLimit=2
        ///s.PriorityAsyncLoadingExtraTime=1
        ///s.UnregisterComponentsTimeLimit=2
        ///s.LevelStreamingActorsUpdateTimeLimit=2
        ///s.PriorityLevelStreamingActorsUpdateExtraTime=1
        ///s.ContinuouslyIncrementalGCWhileLevelsPendingPurge=0
        ///s.F [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Profile1 {
            get {
                return ResourceManager.GetString("Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemSettings]
        ///r.LevelStreamingDistanceScale=10
        ///r.ViewDistanceScale=10
        ///r.StaticMeshLODDistanceScale=0.25
        ///r.SkeletalMeshLODBias=-3
        ///r.LandscapeLODBias=-1
        ///r.LandscapeLODDistributionScale=3
        ///r.LandscapeLOD0DistributionScale=3
        ///r.LODFadeTime=2
        ///r.UITextureLODBias=-1
        ///rhi.SyncInterval=1
        ///rhi.SyncSlackMS=0
        ///r.GTSyncType=2
        ///r.OneFrameThreadLag=1
        ///r.VSync=1
        ///r.Streaming.NumStaticComponentsProcessedPerFrame=10
        ///s.LevelStreamingComponentsUnregistrationGranularity=5
        ///s.LevelStreamingComponentsRegistrationGranul [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Profile2 {
            get {
                return ResourceManager.GetString("Profile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemSettings]
        ///r.VT.MaxAnisotropy=16
        ///r.MaxAnisotropy=16
        ///r.PostProcessAAQuality=5
        ///r.TemporalAA.Algorithm=1
        ///r.TemporalAASharpness=0.0
        ///r.TemporalAASamples=16
        ///r.TemporalAADynamicSharpen=0.0
        ///r.TemporalAACurrentFrameWeight=0.00
        ///r.Tonemapper.GrainQuantization=0
        ///r.ToneMapper.Sharpen=0.0
        ///r.Shadow.Denoiser=1
        ///r.AmbientOcclusion.Denoiser=1
        ///r.Shadow.RadiusThreshold=0
        ///r.Shadow.MaxResolution=3072
        ///r.Shadow.MinResolution=2048
        ///r.Shadow.MaxCSMResolution=3072
        ///r.Shadow.MinCSMResolution=2048
        ///r.LevelStreamingD [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Profile3 {
            get {
                return ResourceManager.GetString("Profile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemSettings]
        ///r.VT.MaxAnisotropy=16
        ///r.MaxAnisotropy=16
        ///r.PostProcessAAQuality=6
        ///r.TemporalAA.Algorithm=1
        ///r.TemporalAASharpness=0.0
        ///r.TemporalAASamples=64
        ///r.TemporalAADynamicSharpen=0.0
        ///r.TemporalAACurrentFrameWeight=0.00 
        ///r.Tonemapper.GrainQuantization=0
        ///r.ToneMapper.Sharpen=0.0
        ///r.Shadow.Denoiser=1
        ///r.AmbientOcclusion.Denoiser=1
        ///r.Shadow.RadiusThreshold=0
        ///r.Shadow.MaxResolution=4096
        ///r.Shadow.MinResolution=4096
        ///r.Shadow.MaxCSMResolution=4096
        ///r.Shadow.MinCSMResolution=4096
        ///r.LevelStreaming [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Profile4 {
            get {
                return ResourceManager.GetString("Profile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemSettings]
        ///r.VT.MaxAnisotropy=16
        ///r.MaxAnisotropy=16
        ///r.PostProcessAAQuality=6
        ///r.TemporalAA.Algorithm=1
        ///r.TemporalAASharpness=0.0
        ///r.TemporalAADynamicSharpen=0.0
        ///r.Tonemapper.GrainQuantization=0
        ///r.ToneMapper.Sharpen=2.0
        ///r.Shadow.Denoiser=1
        ///r.AmbientOcclusion.Denoiser=1
        ///r.Shadow.RadiusThreshold=0
        ///r.Shadow.MaxResolution=4096
        ///r.Shadow.MinResolution=4096
        ///r.Shadow.MaxCSMResolution=4096
        ///r.Shadow.MinCSMResolution=4096
        ///r.LevelStreamingDistanceScale=10
        ///r.ViewDistanceScale=10
        ///r.StaticMeshLODDista [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Profile5 {
            get {
                return ResourceManager.GetString("Profile5", resourceCulture);
            }
        }
    }
}
